### ISSUE TITLE
Register package

### ISSUE THREAD

**Issue by mohdibntarek** [ThummeTo/ForwardDiffChainRules.jl#3]
@JuliaRegistrator register

**Comment by mohdibntarek** [comment]
@ThummeTo you need to turn on JuliaRegistrator for this repo and then write the above message in a comment below.

**Comment by mohdibntarek** [comment]
https://github.com/JuliaRegistries/Registrator.jl

**Comment by ThummeTo** [comment]
Pending registration ;-)

**Comment by mohdibntarek** [comment]
Nice, congratulations! I will close this issue.

**Comment by ThummeTo** [comment]
Last time I registered something, there was a waiting time of 3 days to allow others to announce concerns with the package/naming. So this issue might be stille bw open a little.

Unregistered packages can be used in package mode via `add "https://github.com/ThummeTo/ForwardDiffChainRules.jl"` or `Pkg.add("https://github.com/ThummeTo/ForwardDiffChainRules.jl")` until release.

**Comment by mohdibntarek** [comment]
Ya it takes 3 days but it's pretty routine. I don't expect any trouble.

**Comment by ThummeTo** [comment]
> Nice, congratulations! I will close this issue.

Congratulations to you too ;-)
