### ISSUE TITLE
ERROR: syntax: unexpected semicolon in tuple around ForwardDiffChainRules.jl:48

### ISSUE THREAD

**Issue by jbrea** [ThummeTo/ForwardDiffChainRules.jl#5]
Related to #4 
```julia
using ChainRulesCore, ForwardDiff, ForwardDiffChainRules, ChainRulesTestUtils
g(f, x; kwargs...) = f(x; kwargs...)
function ChainRulesCore.frule((_, _, Δx), ::typeof(g), f, x; kwargs...)
    y = g(f, x; kwargs...)
    return y, f(x) * Δx
end
test_frule(g, exp, .4)
julia> @ForwardDiff_frule g(f, x::ForwardDiff.Dual; kwargs...)
ERROR: syntax: unexpected semicolon in tuple around ~/.julia/packages/ForwardDiffChainRules/Hgko1/src/ForwardDiffChainRules.jl:48
Stacktrace:
 [1] top-level scope
   @ REPL[9]:1

**Comment by mohamed82008** [comment]
Should be fixed with DifferentiableFlatten 0.1.1. I will make a PR to bump its lower bound here once it's registered https://github.com/JuliaRegistries/General/pull/70696.

**Comment by mohdibntarek** [comment]
ChainRules does not support kwargs in frules so I don't think we should allow kwargs in the function signature used here. The error can be more informative though.

**Comment by mohdibntarek** [comment]
Looks like some frules have kwargs defined https://github.com/JuliaDiff/ChainRules.jl/blob/1f4a8a9d86c79f024a911f61aa180bdc094bb8a3/src/rulesets/LinearAlgebra/factorization.jl#L23.

**Comment by mohdibntarek** [comment]
https://github.com/ThummeTo/ForwardDiffChainRules.jl/pull/6
